artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://archive.ics.uci.edu/dataset/186/wine+quality
  local_data_file: artifacts/data_ingestion/data.zip
  